# Generated by Django 3.2.3 on 2021-06-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_gretting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gretting',
            name='temp',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
