version: "3.9"
services: 
    alert:
        build: alert/.
        port: 
            - "5000:5000",
        links: 
            - auth
            - db
    auth:
        build: auth/.
        port: 
            - "7000:7000"
    health:
        build: health/.
        port: 
            - "3500:3500"
        links: 
            - auth
            - alert
    db:
        image: mysql
        environment:
                MYSQL_DATABASE: "alerts"
                MYSQL_USER: 'developer'
                MYSQL_PASSWORD: 'rootcodigo'
                MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'