# Generated by Django 3.2.4 on 2021-06-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210609_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(null=True, to='blog.HashTag'),
        ),
    ]
