# Generated by Django 3.2.4 on 2021-06-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210624_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(null=True, upload_to='questions'),
        ),
    ]
